use_frameworks!

target 'collection_flow_layout_Example' do
  pod 'collection_flow_layout', :path => '../'

  target 'collection_flow_layout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
