use_frameworks!

target 'collection_flow_layout_Example' do
  pod 'collection_flow_layout', :path => '../'
  pod 'collection_flow_layout/TagsLayout', :path => '../'
  pod 'collection_flow_layout/PinterestLayout', :path => '../'
  pod 'collection_flow_layout/Px500Layout', :path => '../'
  pod 'collection_flow_layout/InstagramLayout', :path => '../'

  target 'collection_flow_layout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'Fakery', '~> 3.3'
  end
end
